/*
 * This source file was generated by the Gradle 'init' task
 */
package javaopenglgameengine;

import org.lwjgl.Version;

import javaopenglgameengine.core.WindowManager;

public class App {

    public static void main(String[] args) {
        System.out.println(Version.getVersion());

        WindowManager window = new WindowManager("test", 1280, 720, false);
        window.init();

        while(!window.windowShouldClose()) {
            window.update();
        }

        window.cleanup();
    }
}
